-- ATHLTH realtime presence, live workouts and privacy-first live Ghost support.
-- Live location is opt-in, viewer-scoped and short-lived.

alter table public.profile_social_settings
    add column if not exists show_online_status boolean not null default false,
    add column if not exists share_live_workout_location boolean not null default false;

alter table public.social_presence
    add column if not exists last_seen_at timestamptz,
    add column if not exists online_until timestamptz;

update public.social_presence
set
    last_seen_at = coalesce(last_seen_at, updated_at),
    online_until = coalesce(online_until, updated_at)
where last_seen_at is null
   or online_until is null;

create table if not exists public.live_workout_sessions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.profiles(id) on delete cascade,
    workout_id uuid,
    activity_kind text not null check (
        activity_kind in ('running', 'walking', 'hiking', 'cycling')
    ),
    title text not null check (char_length(title) between 1 and 120),
    status text not null default 'active' check (
        status in ('active', 'finished', 'cancelled')
    ),
    ghost_enabled boolean not null default true,
    started_at timestamptz not null default now(),
    ended_at timestamptz,
    updated_at timestamptz not null default now(),
    expires_at timestamptz not null default (now() + interval '6 hours')
);

create unique index if not exists live_workout_sessions_one_active_per_user_idx
    on public.live_workout_sessions(user_id)
    where status = 'active';

create index if not exists live_workout_sessions_active_updated_idx
    on public.live_workout_sessions(status, updated_at desc);

create table if not exists public.live_workout_points (
    id bigint generated by default as identity primary key,
    session_id uuid not null references public.live_workout_sessions(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    captured_at timestamptz not null,
    latitude double precision not null check (latitude between -90 and 90),
    longitude double precision not null check (longitude between -180 and 180),
    altitude_meters double precision,
    horizontal_accuracy_meters double precision,
    distance_meters double precision not null default 0 check (distance_meters >= 0),
    elapsed_seconds double precision not null default 0 check (elapsed_seconds >= 0),
    expires_at timestamptz not null default (now() + interval '6 hours')
);

create index if not exists live_workout_points_session_time_idx
    on public.live_workout_points(session_id, captured_at desc);

create index if not exists live_workout_points_expiry_idx
    on public.live_workout_points(expires_at);

alter table public.live_workout_sessions enable row level security;
alter table public.live_workout_points enable row level security;

revoke all on public.live_workout_sessions from anon;
revoke all on public.live_workout_points from anon;
revoke all on public.live_workout_sessions from authenticated;
revoke all on public.live_workout_points from authenticated;

grant select, insert, update(status, ended_at, updated_at, expires_at, ghost_enabled)
    on public.live_workout_sessions to authenticated;
grant select, insert, delete
    on public.live_workout_points to authenticated;

create schema if not exists private;
revoke all on schema private from public;
revoke all on schema private from anon;
grant usage on schema private to authenticated;

create or replace function private.can_view_social_presence(p_owner uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select
        (select auth.uid()) is not null
        and (
            p_owner = (select auth.uid())
            or (
                coalesce(
                    (
                        select s.show_online_status
                        from public.profile_social_settings s
                        where s.user_id = p_owner
                    ),
                    false
                )
                and not exists (
                    select 1
                    from public.user_blocks b
                    where
                        (b.blocker_id = p_owner and b.blocked_id = (select auth.uid()))
                        or
                        (b.blocker_id = (select auth.uid()) and b.blocked_id = p_owner)
                )
                and (
                    coalesce(
                        (
                            select s.profile_visibility
                            from public.profile_social_settings s
                            where s.user_id = p_owner
                        ),
                        'private'
                    ) = 'public'
                    or exists (
                        select 1
                        from public.profile_follows f
                        where f.follower_id = (select auth.uid())
                          and f.following_id = p_owner
                    )
                )
            )
        );
$$;

create or replace function private.can_view_live_workout(p_owner uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select
        (select auth.uid()) is not null
        and (
            p_owner = (select auth.uid())
            or (
                coalesce(
                    (
                        select s.share_live_workout_location
                        from public.profile_social_settings s
                        where s.user_id = p_owner
                    ),
                    false
                )
                and not exists (
                    select 1
                    from public.user_blocks b
                    where
                        (b.blocker_id = p_owner and b.blocked_id = (select auth.uid()))
                        or
                        (b.blocker_id = (select auth.uid()) and b.blocked_id = p_owner)
                )
                and exists (
                    select 1
                    from public.profile_follows me
                    join public.profile_follows them
                      on them.follower_id = p_owner
                     and them.following_id = (select auth.uid())
                    where me.follower_id = (select auth.uid())
                      and me.following_id = p_owner
                )
            )
            or exists (
                select 1
                from public.ghost_race_challenges g
                where g.status = 'accepted'
                  and g.expires_at > now()
                  and (
                      (g.sender_id = p_owner and g.recipient_id = (select auth.uid()))
                      or
                      (g.recipient_id = p_owner and g.sender_id = (select auth.uid()))
                  )
            )
        );
$$;

revoke all on function private.can_view_social_presence(uuid) from public;
revoke all on function private.can_view_social_presence(uuid) from anon;
grant execute on function private.can_view_social_presence(uuid) to authenticated;

revoke all on function private.can_view_live_workout(uuid) from public;
revoke all on function private.can_view_live_workout(uuid) from anon;
grant execute on function private.can_view_live_workout(uuid) to authenticated;

drop policy if exists "presence visible by privacy" on public.social_presence;
create policy "presence visible by privacy"
on public.social_presence
for select
to authenticated
using (private.can_view_social_presence(user_id));

drop policy if exists "live workout sessions owner insert" on public.live_workout_sessions;
create policy "live workout sessions owner insert"
on public.live_workout_sessions
for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "live workout sessions owner update" on public.live_workout_sessions;
create policy "live workout sessions owner update"
on public.live_workout_sessions
for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

drop policy if exists "live workout sessions viewer select" on public.live_workout_sessions;
create policy "live workout sessions viewer select"
on public.live_workout_sessions
for select
to authenticated
using (
    expires_at > now()
    and private.can_view_live_workout(user_id)
);

drop policy if exists "live workout points owner insert" on public.live_workout_points;
create policy "live workout points owner insert"
on public.live_workout_points
for insert
to authenticated
with check (
    user_id = (select auth.uid())
    and exists (
        select 1
        from public.live_workout_sessions s
        where s.id = session_id
          and s.user_id = (select auth.uid())
          and s.status = 'active'
    )
);

drop policy if exists "live workout points owner delete" on public.live_workout_points;
create policy "live workout points owner delete"
on public.live_workout_points
for delete
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "live workout points viewer select" on public.live_workout_points;
create policy "live workout points viewer select"
on public.live_workout_points
for select
to authenticated
using (
    expires_at > now()
    and private.can_view_live_workout(user_id)
);

create or replace function public.prune_live_workout_data()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    delete from public.live_workout_points
    where expires_at <= now();

    update public.live_workout_sessions
    set
        status = 'cancelled',
        ended_at = coalesce(ended_at, now()),
        updated_at = now()
    where status = 'active'
      and updated_at < now() - interval '10 minutes';

    delete from public.live_workout_sessions
    where expires_at <= now()
      and status <> 'active';
end;
$$;

revoke all on function public.prune_live_workout_data() from public;
revoke all on function public.prune_live_workout_data() from anon;
grant execute on function public.prune_live_workout_data() to authenticated;

do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'live_workout_sessions'
    ) then
        alter publication supabase_realtime add table public.live_workout_sessions;
    end if;

    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'live_workout_points'
    ) then
        alter publication supabase_realtime add table public.live_workout_points;
    end if;

    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'social_presence'
    ) then
        alter publication supabase_realtime add table public.social_presence;
    end if;
end
$$;
