-- 20 newly authored, original ATHLTH core exercises, checked against
-- the 637-entry RepDB free catalog and existing ATHLTH names (2026-10-10).
-- Descriptions/instructions are written for ATHLTH. Artwork is rendered
-- by ATHLTH's own SwiftUI vector silhouettes, not RepDB photos.
-- Repeatable/idempotent; never replace or duplicate existing names.
INSERT INTO public.exercise_catalog
 (id, slug, name, summary, instructions, primary_muscles, secondary_muscles,
  equipment, category, difficulty, source_label, sort_order, is_published)
SELECT gen_random_uuid(), v.slug, v.name, v.summary, v.instructions,
       v.primary_muscles, v.secondary_muscles, v.equipment,
       v.category, v.difficulty, v.source_label, v.sort_order, true
FROM (VALUES
  ('athlth-core-plank-shoulder-tap', 'Plank Shoulder Tap', 'Tap the opposite shoulder while keeping the hips steady.', ARRAY['Start in a high plank, wrists under shoulders.','Tap one shoulder with the opposite hand without letting the hips swing.','Alternate sides slowly.']::text[], ARRAY['Core']::text[], ARRAY['Shoulders']::text[], ARRAY['Bodyweight']::text[], 'core', 'Beginner', 'ATHLTH Original · Core', 200),
  ('athlth-core-plank-jack', 'Plank Jack', 'Controlled foot hops from a stable high plank.', ARRAY['Start in a high plank with feet together.','Hop feet out to the sides while bracing the trunk.','Hop the feet back together and land softly.']::text[], ARRAY['Core']::text[], ARRAY['Shoulders']::text[], ARRAY['Bodyweight']::text[], 'core', 'Intermediate', 'ATHLTH Original · Core', 201),
  ('athlth-core-plank-walkout', 'Plank Walkout', 'Walk your hands to a plank and back.', ARRAY['Stand tall and fold from the hips toward the floor.','Walk the hands forward into a strong plank.','Walk back and stand up slowly.']::text[], ARRAY['Core']::text[], ARRAY['Shoulders']::text[], ARRAY['Bodyweight']::text[], 'core', 'Beginner', 'ATHLTH Original · Core', 202),
  ('athlth-core-rkc-plank', 'RKC Plank', 'A deliberately high-tension forearm plank.', ARRAY['Place elbows beneath shoulders and brace the trunk.','Tighten abs and glutes while gently pulling elbows toward toes.','Breathe calmly and stop before posture breaks.']::text[], ARRAY['Core']::text[], ARRAY['Glutes']::text[], ARRAY['Bodyweight']::text[], 'core', 'Intermediate', 'ATHLTH Original · Core', 203),
  ('athlth-core-hollow-body-rock', 'Hollow Body Rock', 'Controlled rocking in a hollow-body position.', ARRAY['Lie on the back with lower back gently pressed toward the floor.','Raise shoulders and legs to hold a hollow shape.','Rock a few centimeters without changing body shape.']::text[], ARRAY['Core']::text[], ARRAY['Hip Flexors']::text[], ARRAY['Bodyweight']::text[], 'core', 'Intermediate', 'ATHLTH Original · Core', 204),
  ('athlth-core-toe-touch-crunch', 'Toe Touch Crunch', 'Reach upward toward raised toes to train trunk flexion.', ARRAY['Lie on the back with legs raised toward the ceiling.','Reach the hands toward the toes, lifting shoulder blades.','Lower shoulders with control.']::text[], ARRAY['Core']::text[], ARRAY['Hip Flexors']::text[], ARRAY['Bodyweight']::text[], 'core', 'Beginner', 'ATHLTH Original · Core', 205),
  ('athlth-core-standing-cable-woodchop', 'Standing Cable Woodchopper', 'High-to-low diagonal cable movement against trunk rotation.', ARRAY['Stand sideways to a cable handle set high.','Pull diagonally across the torso while bracing the abdomen.','Return slowly and complete both sides.']::text[], ARRAY['Core']::text[], ARRAY['Shoulders']::text[], ARRAY['Cable Machine']::text[], 'core', 'Intermediate', 'ATHLTH Original · Core', 206),
  ('athlth-core-half-kneeling-cable-chop', 'Half-Kneeling Cable Chop', 'A diagonal cable chop with one knee on the floor.', ARRAY['Kneel tall with one knee down, cable above shoulder level.','Pull the handle down and across without leaning.','Control the return, then switch sides.']::text[], ARRAY['Core']::text[], ARRAY['Glutes']::text[], ARRAY['Cable Machine']::text[], 'core', 'Intermediate', 'ATHLTH Original · Core', 207),
  ('athlth-core-pallof-step-out', 'Pallof Step-Out', 'An anti-rotation step away from a cable anchor.', ARRAY['Hold a cable handle against the chest, standing side-on.','Press arms forward and take a measured side step.','Resist twisting and step slowly back.']::text[], ARRAY['Core']::text[], ARRAY['Glutes']::text[], ARRAY['Cable Machine']::text[], 'core', 'Intermediate', 'ATHLTH Original · Core', 208),
  ('athlth-core-banded-dead-bug-pulldown', 'Banded Dead Bug Pulldown', 'Opposing arm and leg control under band resistance.', ARRAY['Lie on the back holding a resistance band anchored above the head.','Pull the band toward the ribs and lift the knees over the hips.','Extend one leg slowly without arching, then alternate.']::text[], ARRAY['Core']::text[], ARRAY['Hip Flexors']::text[], ARRAY['Resistance Band']::text[], 'core', 'Intermediate', 'ATHLTH Original · Core', 209),
  ('athlth-core-bird-dog-row', 'Bird Dog Dumbbell Row', 'A supported single-arm row that challenges trunk stability.', ARRAY['Support one hand and opposite knee on a stable bench.','Reach the free leg back and row a light dumbbell.','Keep the hips square and complete both sides.']::text[], ARRAY['Core']::text[], ARRAY['Back']::text[], ARRAY['Dumbbell','Bench']::text[], 'core', 'Intermediate', 'ATHLTH Original · Core', 210),
  ('athlth-core-side-plank-hip-dip', 'Side Plank Hip Dip', 'Lower and raise the hips from a supported side plank.', ARRAY['Begin in a straight forearm side plank.','Lower the pelvis a little toward the floor.','Press the hip upward with control and repeat.']::text[], ARRAY['Core']::text[], ARRAY['Glutes']::text[], ARRAY['Bodyweight']::text[], 'core', 'Intermediate', 'ATHLTH Original · Core', 211),
  ('athlth-core-side-plank-reach-through', 'Side Plank Reach-Through', 'Upper-body rotation while the hips stay lifted in a side plank.', ARRAY['Hold a side plank with the upper arm reaching upward.','Thread the top arm beneath the ribcage.','Open back to the starting position without sagging.']::text[], ARRAY['Core']::text[], ARRAY['Shoulders']::text[], ARRAY['Bodyweight']::text[], 'core', 'Intermediate', 'ATHLTH Original · Core', 212),
  ('athlth-core-bear-plank-shoulder-tap', 'Bear Plank Shoulder Tap', 'Alternating shoulder taps from a hovering quadruped position.', ARRAY['Start on hands and knees, lifting knees just off the ground.','Touch the opposite shoulder with one hand.','Stay level, replace the hand, and alternate.']::text[], ARRAY['Core']::text[], ARRAY['Shoulders']::text[], ARRAY['Bodyweight']::text[], 'core', 'Intermediate', 'ATHLTH Original · Core', 213),
  ('athlth-core-windshield-wiper', 'Lying Windshield Wipers', 'Move raised legs side to side with abdominal control.', ARRAY['Lie on the back with arms spread for stability.','Raise the legs and lower them a short way toward one side.','Return to center and repeat the other way.']::text[], ARRAY['Core']::text[], ARRAY['Hip Flexors']::text[], ARRAY['Bodyweight']::text[], 'core', 'Advanced', 'ATHLTH Original · Core', 214),
  ('athlth-core-stir-the-pot', 'Stir the Pot', 'Small controlled circles in a forearm plank on a ball.', ARRAY['Place forearms on a stable exercise ball in plank position.','Draw small circles with the forearms without moving the hips.','Reverse direction after several controlled circles.']::text[], ARRAY['Core']::text[], ARRAY['Shoulders']::text[], ARRAY['Stability Ball']::text[], 'core', 'Intermediate', 'ATHLTH Original · Core', 215),
  ('athlth-core-swiss-ball-body-saw', 'Stability Ball Body Saw', 'Shift forward and backward in a ball-supported forearm plank.', ARRAY['Rest forearms on a stability ball and brace the trunk.','Shift slowly backward, then forward a small distance.','Keep the lower back neutral throughout.']::text[], ARRAY['Core']::text[], ARRAY['Shoulders']::text[], ARRAY['Stability Ball']::text[], 'core', 'Intermediate', 'ATHLTH Original · Core', 216),
  ('athlth-core-copenhagen-plank', 'Copenhagen Plank', 'A side plank emphasizing the inner thigh and trunk.', ARRAY['Support the top leg on a sturdy, padded bench.','Lift the pelvis and draw the lower leg toward the bench.','Keep the hips aligned and change sides after the set.']::text[], ARRAY['Adductors']::text[], ARRAY['Core','Glutes']::text[], ARRAY['Bench']::text[], 'core', 'Advanced', 'ATHLTH Original · Core', 217),
  ('athlth-core-suitcase-march', 'Suitcase March', 'Slow single-sided loaded marching without trunk lean.', ARRAY['Hold a dumbbell or kettlebell in one hand.','March in place with slow, controlled knee lifts.','Stay upright and switch hands after the set.']::text[], ARRAY['Core']::text[], ARRAY['Glutes']::text[], ARRAY['Dumbbell','Kettlebell']::text[], 'core', 'Beginner', 'ATHLTH Original · Core', 218),
  ('athlth-core-standing-knee-elbow-crunch', 'Standing Knee-to-Elbow Crunch', 'Standing alternating side bends toward the lifted knee.', ARRAY['Stand upright with fingertips near the ears.','Bring one knee toward its same-side elbow while bending slightly.','Return tall and alternate without pulling on the neck.']::text[], ARRAY['Core']::text[], ARRAY['Hip Flexors']::text[], ARRAY['Bodyweight']::text[], 'core', 'Beginner', 'ATHLTH Original · Core', 219)
) AS v(slug, name, summary, instructions, primary_muscles, secondary_muscles,
       equipment, category, difficulty, source_label, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_catalog e
  WHERE lower(regexp_replace(e.name, '[^a-z0-9]', '', 'g')) =
        lower(regexp_replace(v.name, '[^a-z0-9]', '', 'g'))
)
ON CONFLICT (slug) DO NOTHING;
